name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm test
      - run: ls ${{ github.workspace }}/dist
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.NSE_NETTIME_CLIENT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
